# Use current version of Node.js
image: node:current-alpine

# Install dependencies
before_script:
  - npm install

# Cache dependencies in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

# Run tests
test:
  stage: test
  script:
    - npm run test
